id: ADC02B34B
title: 'Light of Compassion: A Prayer to the Wisdom Ḍākinīs'
type: translation
pechas:
- I6A5A8F56
- I183AB623
- IEB2491A0
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:38:08.673004
  last_modified_at: 2023-01-04 11:38:08.673010
  collections:
  - Dilgo Khyentse Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I6A5A8F56/5038: '7158'
  I183AB623/C5AA: '7158'
  IEB2491A0/4A88: '7158'
